version: '2.3'

services:
  nginx:
    image: nginx:1.19.6
    ports:
      - 80:80
    restart: always
    volumes:
      - ./compose-data/static/:/static/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  # depends_on:
  #   landing

  lp:
    build:
      context:  .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./compose-data/static/:/static/
